version: '3.8'

services:
  scraper:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
    command: ["python", "Scraper/index_new.py"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local